### PR TITLE
General code cleanup

### PR DESCRIPTION
**Pull request by mvysny**
Hi, it is usual to have Intellij files in .gitignore and not committed to git; also removed generated output.css from git; also I have refactored MyUI a bit to avoid NullPointerExceptions when the navigation items are clicked.

### CODE REVIEW

**Comment by jouni** [comment]
@mvysny, hey, did you delete your fork with this patch?

**Comment by jouni** [comment]
I think I can still merge this, though, just wanted to ask :)

**Comment by jouni** [comment]
I merged this PR manually in dc1a6ddc140f47b1de70a16d00c3a0bfefd779cf and cffc5427d7e72458d3799393f7b4736ffe300321

**Comment by mvysny** [comment]
Ooops sorry about that. But actually I have not deleted the repository, but it was probably made private. And now there is this warning:

> This repository is currently disabled. The repository this private fork was created from has been made public. To protect your code’s privacy, the fork is now a private repository under your account’s ownership.

It's probaby because I have not paid for github private repos, so it got disabled. However I'll make it public since this repo is also public. Done.

**Pull request closed without merging**
